services:
  postgres:
    image: postgres:16
    container_name: schooljeyix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TheKingIsComing
      POSTGRES_DB: scolarjeyix
    ports:
      - "5433:5432"
    volumes:
      - schooljeyix_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: schooljeyix_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: schooljeyix_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7.2
    container_name: schooljeyix_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redispass
    command: ["redis-server", "--requirepass", "redispass"]
    ports:
      - "6379:6379"
    volumes:
      - schooljeyix_redis_data:/data

volumes:
  schooljeyix_data:
  schooljeyix_redis_data:
